# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '7_SOPT_Social_Login' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 7_SOPT_Social_Login

    pod 'FBSDKLoginKit'
    
end
